=== benheroblaw/text-viewer/devtools/meta_schema.json
{
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "examples": [
        ""
      ]
    },
    "author": {
      "type": "string",
      "examples": [
        "benheroblaw"
      ]
    },
    "title": {
      "type": "string",
      "examples": [
        "test stuff"
      ]
    },
    "rating": {
      "type": "integer",
      "examples": [
        1
      ]
    },
    "warnings": {
      "type": "string",
      "examples": [
        "swearing and obscenities"
      ]
    },
    "credits": {
      "type": "string",
      "examples": [
        "benheroblaw for writing the text viewer"
      ]
    },
    "links": {
      "type": "string",
      "examples": [
        "https://benheroblaw.github.io/"
      ],
      "format": "uri"
    }
  },
  "required": [
    "rating"
  ],
  "$schema": "https://json-schema.org/draft/2020-12/schema"
}

=== benheroblaw/text-viewer/content/zzz-testing/meta.json
{
  "$schema": "https://benheroblaw.github.io/meta_schema.json",
  "author": "benheroblaw",
  "title": "_test stuff",
  "rating": 1,
  "warnings": "swearing and obscenities ;) {comes with coding :P}",
  "credits": "benheroblaw for writing the text viewer",
  "links": "https://benheroblaw.github.io/, but that's prolly where you got this :P"
}

=== benheroblaw/text-viewer/content/zzz-zzz-zzz-testing/meta.json
{
  "$schema": "https://benheroblaw.github.io/meta_schema.json",
  "author": "benheroblaw",
  "title": "_test stuff",
  "rating": 1,
  "warnings": "swearing and obscenities ;) {comes with coding :P}",
  "credits": "me for writing the text viewer :3",
  "links": "https://benheroblaw.github.io/, but that's prolly where you got this :P"
}
